#!/bin/bash
# shellcheck disable=SC2141

exec {_fd}<"${XDG_CONFIG_DIR:-${HOME}/.config}"/Nextcloud/nextcloud.cfg

while IFS='\=' read -a _line -r -u $_fd
do
  [ ${#_line[@]} -eq 5 ] || continue
  [ "${_line[1]}" = Folders ] || continue
  [ "${_line[3]}" = localPath ] || continue

  _dir="${_line[4]}"/v2ray/enabled
  [ -d "${_dir}" ] || continue

  CONFDIR="$(realpath "${_dir}")"
  export CONFDIR
  break
done

exec {_fd}>&-
