#!/bin/bash

if pulseaudio --check; then
	exit 0
fi

(unset PULSE_SERVER && pulseaudio --start)

sleep 1

tor --hush -f $XDG_CONFIG_HOME/tor/torrc \
	--ControlSocket $XDG_CONFIG_HOME/tor/control \
	--Log notice\ file\ $XDG_CONFIG_HOME/tor/log \
	--DataDirectory $XDG_CACHE_HOME/tor &

mpd --no-daemon &
