theme = "kanagawa"

[editor]
line-number = "relative"
color-modes = true
soft-wrap.enable = true
rulers = [80, 100]

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "│"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"