[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }

[language.debugger]
name = "platformio"
transport = "stdio"
command = "piodebuggdb"

[[language.debugger.templates]]
name = "openocd"
request = "launch"
completion = [ "--", "-x", ".pioinit" ]
args = { runInTerminal = true }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "    " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'|' = '|'
'<' = '>'

[language.config.checkOnSave]
command = "clippy"
