[language-server.rust-analyzer.config]
checkOnSave.command = "clippy"
imports.prefix = "self"

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }

[language.debugger]
name = "platformio"
transport = "stdio"
command = "piodebuggdb"

[[language.debugger.templates]]
name = "openocd"
request = "launch"
completion = ["--", "-x", ".pioinit"]
args = { runInTerminal = true }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "    " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'|' = '|'
'<' = '>'

[[language]]
name = "php"
# language-server.command = "php-language-server.php"

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
