directory: ../../music
plugins: convert fetchart embedart thumbnails scrub permissions mbsubmit
import:
    move: yes
    from_scratch: yes
languages: en
match:
    preferred:
        countries: ['US', 'GB|UK']
        media: ['CD', 'Digital Media|File']
        original_year: yes
paths:
    default: $albumartist/$original_year.$original_month. $album/$track. $title
convert:
    format: opus
    formats:
        opus:
            command: ffmpeg -i $source -y -c:a libopus -b:a 64k $dest
            extension: opus
        vorbis:
            command: ffmpeg -i $source -y -c:a libvorbis -q:a 5.5 $dest
            extension: ogg
        mp3: sh -c "ffmpeg -i '$source' -f wav - | lame -V 2 --noreplaygain - '$dest'"
mbsubmit:
    threshold: strong
