#!/bin/bash
# -*- coding: utf-8 -*-
# vim: fenc=utf-8 ts=4 noet sw=4 sts=4 ft=sh

# bash_profile: executed by bash(1) for login shells.
# normally this is executed when $PWD=$HOME.

. .env

unset OLDPWD

logdir=$XDG_CONFIG_HOME/bash

for item in sway tmux; do
	if [ $TERM = $item ]; then
		if cd $XDG_CONFIG_HOME/$item; then
			logdir=$PWD
		else
			printf "ERROR: $$TERM is set to '$TERM' but it's directory does" \
				"not exist, falling back to plain shell" >&2
		fi

		break
	fi
done

setsid -f $XDG_CONFIG_HOME/autorun >$logdir/log 2>&1

if [ "${OLDPWD+x}" ]; then
	if [ -x ./login ]; then
		unset TERM OLDPWD
		exec dbus-launch --exit-with-session ./login >>$logdir/log 2>&1
	fi

	printf "ERROR: $$TERM is set to '$TERM' but the following is not an" \
		"executable:\n\t$(realpath ./login)" >&2
fi

. $XDG_CONFIG_HOME/bash/config
